apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-feedback-backend.fullname" . }}
  labels:
    {{- include "jitsi-feedback-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jitsi-feedback-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jitsi-feedback-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: dbPort
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: dbName
            - name: UVS_AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: UVS_AUTH_TOKEN
            - name: SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: dbSslMode
            - name: OIDC_VALIDATION_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: oidcValidationUrl
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: MATRIX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: matrixServerName
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
