name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version: '1.19'

      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make test